/**
 * Các đơn vị hành chính CŨ đã sáp nhập thành mỗi xã/phường/đặc khu hiện nay.
 *
 * Dùng để nhắc người đăng tin nhận ra khu vực của mình: sau sáp nhập 2025 nhiều người vẫn
 * quen tên cũ ("Thị xã Đức Phổ") trong khi hệ thống chỉ còn tên mới ("Phường Đức Phổ").
 *
 * Khoá là district_id trong DB (= 10000 + mã khoá trong prisma/seed-data/qn-96-units.json).
 * Đơn vị cũ trùng tên với đơn vị mới đã được lược bỏ vì không mang thêm thông tin.
 *
 * KHÔNG dùng để suy ra địa chỉ: một xã mới gộp từ nhiều xã cũ nên ánh xạ ngược là
 * một-nhiều, không xác định được điểm cụ thể thuộc xã cũ nào.
 */
export const FORMER_UNITS: Record<number, string[]> = {
  10241: ["Xã Nghĩa Dõng", "Xã Nghĩa Dũng", "Xã Nghĩa Hà"],
  10295: ["Xã Ba Giang"],
  10300: ["Xã Ba Liên", "Xã Ba Thành"],
  10252: ["Xã Tịnh Bắc", "Xã Tịnh Hiệp", "Xã Tịnh Trà"],
  10293: ["Xã Ba Lế", "Xã Ba Nam"],
  10115: ["Thị trấn Ba Tơ", "Xã Ba Bích", "Xã Ba Cung"],
  10292: ["Xã Ba Ngạc", "Xã Ba Tiêu"],
  10298: ["Xã Ba Điền"],
  10304: ["Ba Xa"],
  10248: ["Xã Bình Mỹ"],
  10244: ["Xã Bình An", "Xã Bình Khương"],
  10117: ["Thị trấn Châu Ổ", "Xã Bình Chánh", "Xã Bình Dương", "Xã Bình Long", "Xã Bình Nguyên", "Xã Bình Thạnh", "Xã Bình Trung"],
  10303: ["Thị trấn Plei Kần", "Xã Đăk Xú", "Xã Pờ Y"],
  10265: ["Xã Trà Bùi", "Xã Trà Tân"],
  10113: ["Phường Chánh Lộ", "Phường Nghĩa Chánh", "Phường Nguyễn Nghiêm", "Phường Trần Hưng Đạo (thành phố Quảng Ngãi)"],
  10299: ["Xã Đăk Ang", "Xã Đăk Dục", "Xã Đăk Nông"],
  10310: ["Lê Lợi", "Nguyễn Trãi", "Phường Trần Hưng Đạo (thành phố Kon Tum)"],
  10308: ["Phường Duy Tân", "Phường Ngô Mây", "Xã Đăk Cấm"],
  10316: ["Thị trấn Đăk Hà", "Xã Đăk La", "Xã Hà Mòn"],
  10285: ["Xã Đăk Tơ Lung"],
  10279: ["Đăk Long"],
  10319: ["Xã Đăk Hring"],
  10290: ["Xã Đăk Kroong"],
  10291: ["Thị trấn Đăk Glei"],
  10294: ["Xã Đăk Man", "Xã Đăk Nhoong"],
  10320: ["Xã Đăk Long (thuộc huyện Đăk Hà)"],
  10321: ["Xã Chư Hreng", "Xã Đăk Blà", "Xã Hòa Bình"],
  10283: ["Thị trấn Đăk Rve", "Xã Đăk Pne"],
  10311: ["Xã Đăk Na"],
  10314: ["Thị trấn Đăk Tô", "Xã Diên Bình", "Xã Pô Kô", "Xã Tân Cảnh"],
  10309: ["Xã Đăk Rơ Ông"],
  10318: ["Xã Đăk Ngọk"],
  10302: ["Xã Ba Khâm", "Xã Ba Trang"],
  10257: ["Xã Hành Đức", "Xã Hành Phước", "Xã Hành Thịnh"],
  10250: ["Xã Bình Châu", "Xã Bình Hiệp", "Xã Bình Tân Phú", "Xã Bình Thanh", "Xã Tịnh Hòa"],
  10263: ["Xã Trà Bình", "Xã Trà Giang", "Xã Trà Phú"],
  10129: ["Phổ Hòa", "Phổ Minh", "Phổ Ninh", "Phổ Vinh", "Phường Nguyễn Nghiêm (thị xã Đức Phổ)"],
  10322: ["Xã Đăk Năng", "Xã Đoàn Kết"],
  10276: ["Ia Đal"],
  10286: ["Xã Ia Dom"],
  10246: ["Xã Phổ Cường", "Xã Phổ Khánh"],
  10284: ["Xã Đăk Ruồng", "Xã Đăk Tờ Re", "Xã Tân Lập"],
  10313: ["Xã Đăk Trăm", "Xã Văn Lem"],
  10280: ["Xã Hiếu", "Xã Ngọk Tem", "Xã Pờ Ê"],
  10306: ["Phường Quang Trung", "Phường Quyết Thắng", "Phường Thắng Lợi", "Phường Thống Nhất", "Phường Trường Chinh"],
  10262: ["Xã Đức Lân", "Xã Đức Phong"],
  10260: ["Xã Đức Hiệp", "Xã Đức Nhuận", "Xã Thắng Lợi"],
  10124: ["Huyện Lý Sơn"],
  10281: ["Xã Đăk Nên", "Xã Đăk Ring"],
  10282: ["Thị trấn Măng Đen", "Xã Đăk Tăng", "Xã Măng Cành"],
  10305: ["Xã Ngọk Lây", "Xã Ngọk Yêu", "Xã Tê Xăng", "Xã Văn Xuôi"],
  10125: ["Xã Long Hiệp", "Xã Long Môn", "Xã Thanh An"],
  10261: ["Xã Đức Chánh", "Xã Đức Minh", "Xã Đức Thạnh"],
  10119: ["Thị trấn Mộ Đức", "Xã Đức Hòa", "Xã Đức Phú", "Xã Đức Tân"],
  10277: ["Mô Rai"],
  10255: ["Xã Nghĩa Điền", "Xã Nghĩa Kỳ", "Xã Nghĩa Thuận"],
  10122: ["Thị trấn Chợ Chùa", "Xã Hành Thuận", "Xã Hành Trung"],
  10242: ["Phường Lê Hồng Phong", "Phường Quảng Phú", "Phường Trần Phú"],
  10296: ["Xã Mường Hoong"],
  10312: ["Xã Kroong", "Xã Vinh Quang"],
  10317: ["Xã Ngọk Wang"],
  10315: ["Xã Đăk Rơ Nga"],
  10245: ["Xã Phổ Nhơn", "Xã Phổ Phong"],
  10259: ["Xã Hành Dũng", "Xã Hành Minh", "Xã Hành Nhân"],
  10278: ["Rờ Kơi"],
  10288: ["Xã Hơ Moong", "Xã Sa Nghĩa"],
  10247: ["Phường Phổ Thạnh", "Xã Phổ Châu"],
  10301: ["Xã Đăk Kan"],
  10289: ["Thị trấn Sa Thầy", "Xã Sa Nhơn", "Xã Sa Sơn"],
  10121: ["Thị trấn Di Lăng", "Xã Sơn Bao", "Xã Sơn Thượng"],
  10269: ["Xã Sơn Nham", "Xã Sơn Thành"],
  10272: ["Xã Sơn Ba"],
  10270: ["Xã Sơn Cao", "Xã Sơn Giang"],
  10275: ["Xã Long Mai", "Xã Long Sơn"],
  10126: ["Xã Sơn Dung", "Xã Sơn Long", "Xã Sơn Tân"],
  10274: ["Xã Sơn Lập", "Xã Sơn Màu", "Xã Sơn Tinh"],
  10273: ["Xã Sơn Bua", "Xã Sơn Liên", "Xã Sơn Mùa"],
  10271: ["Xã Sơn Hải", "Xã Sơn Trung"],
  10127: ["Thị trấn Tịnh Hà", "Xã Tịnh Bình", "Xã Tịnh Sơn"],
  10264: ["Xã Sơn Trà", "Xã Trà Phong", "Xã Trà Xinh"],
  10268: ["Xã Hương Trà", "Xã Trà Bùi", "Xã Trà Tây"],
  10266: ["Xã Trà Hiệp", "Xã Trà Lâm", "Xã Trà Thanh"],
  10258: ["Xã Hành Thiện", "Xã Hành Tín Đông", "Xã Hành Tín Tây"],
  10253: ["Xã Tịnh Phong", "Xã Tịnh Thọ"],
  10239: ["Xã Tịnh Châu", "Xã Tịnh Kỳ", "Xã Tịnh Long", "Xã Tịnh Thiện"],
  10128: ["Thị trấn Trà Xuân", "Xã Trà Sơn", "Xã Trà Thủy"],
  10243: ["Phường Phổ Quang", "Phường Phổ Văn", "Xã Phổ An", "Xã Phổ Thuận"],
  10256: ["Xã Nghĩa Lâm", "Xã Nghĩa Sơn", "Xã Nghĩa Thắng"],
  10251: ["Xã Tịnh Đông", "Xã Tịnh Giang", "Xã Tịnh Minh"],
  10240: ["Xã Tịnh An", "Xã Tịnh Ấn Đông", "Xã Tịnh Ấn Tây"],
  10307: ["Xã Đăk Hà"],
  10123: ["Thị trấn La Hà", "Xã Nghĩa Hòa", "Xã Nghĩa Thương", "Xã Nghĩa Trung"],
  10249: ["Xã Bình Đông", "Xã Bình Hải", "Xã Bình Hòa", "Xã Bình Phước", "Xã Bình Thuận", "Xã Bình Trị"],
  10254: ["Thị trấn Sông Vệ", "Xã Nghĩa Hiệp", "Xã Nghĩa Phương"],
  10297: ["Xã Đăk Choong"],
  10287: ["Xã Ya Tăng", "Xã Ya Xiêr"],
};
