// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // migrate/introspect dùng kết nối TRỰC TIẾP (Supabase port 5432) vì pooler pgbouncer
    // (port 6543) không hỗ trợ. Fallback về DATABASE_URL cho local dev (Postgres thường).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
